spring:
  application:
    name: eurekaserver

  profiles:
    active: dev

  # --------------------------------------------------
  # Config de Config Client
  # --------------------------------------------------
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      profile: ${SPRING_PROFILES_ACTIVE:prod}
      fail-fast: true
      timeout: 30
      refresh:
        enable: true
      retry:
        initial-interval: 3000
        max-interval: 9000
        max-attempts: 3
        multiplier: 1.5
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de RabbitMQ para Spring Cloud Bus
  # --------------------------------------------------
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:"guest"}
    password: ${RABBIT_PASS:"guest"}
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de actuator
  # --------------------------------------------------
management:
  endpoints:
    web:
      base-path: /actuator # Define o path base dos endpoints do actuator (padrão /actuator)
      exposure:
        include: refresh,health,info,metrics,configprops,busenv,busrefresh,busshutdown # Expõe endpoints para monitoramento
  endpoint:
    health:
      show-details: always # Mostra detalhes completos de saúde
    configprops:
      show-values: always # Mostra valores das propriedades de configuração
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de Eureka Server
  # --------------------------------------------------
eureka:
  client:
    register-with-eureka: false # False = Diz ao servidor: "Não tente se registrar em nenhum outro eureka, você é o próprio servidor". (true em prod)
    fetch-registry: false # False = Diz: "Não tente baixar a lista de serviços de outros servidores eureka". (true em prod)
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de logging
  # --------------------------------------------------
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  # --------------------------------------------------


