server:
  port: ${SERVER_PORT:9060}

spring:
  application:
    name: api-notifications


  # --------------------------------------------------
  # Config de Datasource e Pool de Conexões (MariaDb)
  # --------------------------------------------------
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db-notifications}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MARIADB_USER:mariadb}
    password: ${MARIADB_PASSWORD:mariadb}

    hikari:
      autoCommit: false
      pool-name: ${spring.application.name}-hikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 3000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      keepalive-time: 300000
      isolate-internal-queries: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de JPA
  # --------------------------------------------------
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        connection:
          isolation: 2
        cache:
          use_second_level_cache: false
          use_query_cache: false
    open-in-view: false
    show-sql: true
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de Flyway
  # --------------------------------------------------
  flyway:
    # --- Controle de Execução (Obrigatório) ---
    enabled: true # Liga o Flyway no Spring Boot
    baseline-on-migrate: true # a mais segura e usada por 99 % das empresas
    baseline-version: 0       # ou 1, depende da sua convenção
    baseline-description: "Initial structure"
    # --- Localização e Nomenclatura dos Scripts ---
    locations: classpath:flyway/migration,classpath:flyway/testdata # Onde o Flyway procura os scripts (padrão: db/migration)
    sql-migration-prefix: V # Prefixo padrão para migrações versionadas
    sql-migration-separator: __ # Separador entre versão e nome no arquivo SQL
    sql-migration-suffixes: .sql # Suporta apenas arquivos com sufixo .sql
    # --- Validação e Segurança (Produção) ---
    validate-on-migrate: true # [SEGURANÇA] Valida checksums antes de migrar. Antes de aplicar novas migrations, valida que todas as já aplicadas batem com os scripts no classpath. Protege contra alguém apagar ou alterar um script antigo.
    clean-disabled: true # [SEGURANÇA] DESABILITA o comando 'clean' em produção! Impede acidental flyway:clean em prod.
    out-of-order: false # [SEGURANÇA] Não permite migrações fora de ordem
    target: latest # Garantir que migre sempre para a última versão
    connect-retries: 3 # Número de tentativas de conexão antes de falhar
    connect-retries-interval: 5
    # --- Tabela de Schema (Opcional, mas Útil) ---
    table: flyway_schema_history # padrão já é esse, mas deixar explícito.
    schemas: db-notifications # Defina explicitamente o schema/banco. Importante quando há múltiplos databases.
    encoding: UTF-8 # Encoding dos arquivos SQL
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de Kafka
  # --------------------------------------------------
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
    schema.registry.url: http://schema-registry:8081
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

      # === Estratégia de rebalance ===
      partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
      group-id: ${spring.application.name}-v1
      group.instance.id: ${spring.application.name}-${STATEFULSET_POD_INDEX:0}
      session.timeout.ms: 45000

      # === Forma de leitura e garantia de entrega ===
      auto-offset-reset: latest
      enable-auto-commit: false
      # enable-auto-commit false precisa de tópico DLT

      # === Resiliência (funciona com Retries) ===
      request-timeout-ms: 45000

      # === Performance ===
      max-poll-records: 500
      max.poll.interval.ms: 600000

      # === Schema Registry ===
      properties:
        specific.avro.reader: true

    topic:
      events:
        customer-created: events.customer-created-v1
      min.insync.replicas: 2
  # --------------------------------------------------


  # --------------------------------------------------
  # Config Spring Email
  # --------------------------------------------------
  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.juniorsmartins@gmail.com
    password: nrqd slph cgpq tlit
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de Config Client
  # --------------------------------------------------
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      profile: ${SPRING_PROFILES_ACTIVE:prod}
      fail-fast: true
      refresh:
        enable: true
      retry:
        initial-interval: 3000
        max-interval: 9000
        max-attempts: 3
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de Actuator
  # --------------------------------------------------
management:
  endpoints:
    web:
      base-path: /actuator # Define o path base dos endpoints do actuator (padrão /actuator)
      exposure:
        include: refresh,health,info,metrics,configprops,flyway # Expõe endpoints para monitoramento
  endpoint:
    health:
      show-details: always # Mostra detalhes completos de saúde
    configprops:
      show-values: always # Mostra valores das propriedades de configuração
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de Eureka Client
  # --------------------------------------------------
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de SpringDoc/OpenAPI
  # --------------------------------------------------
springdoc:
  api-docs:
    enabled: true
    path: /api-notifications/v3/api-docs
  swagger-ui:
    enebled: true
    path: /swagger-ui/v3/index.html
    url: /api-notifications/v3/api-docs
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de logging
  # --------------------------------------------------
logging:
  level:
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.pool.HikariPool: TRACE
  # --------------------------------------------------

