server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: configserver

#  config:
#    activate:
#      on-profile: dev

  # --------------------------------------------------
  # Config de actuator
  # --------------------------------------------------
management:
  endpoints:
    web:
      base-path: /actuator # Define o path base dos endpoints do actuator (padrão /actuator)
      exposure:
        include: health,info,metrics,liquibase # Expõe endpoints para monitoramento
  endpoint:
    health:
      show-details: always # Mostra detalhes completos de saúde
  # --------------------------------------------------

