server:
  port: ${SERVER_PORT:8761} # Porta padrão do Eureka Server é 8761

spring:
  application:
    name: eurekaserver


  # --------------------------------------------------
  # Config de Config Client
  # --------------------------------------------------
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      profile: ${SPRING_PROFILES_ACTIVE:prod}
      fail-fast: true
      refresh:
        enable: true # Permite buscar automaticamente as configurações atualizadas do servidor de configuração quando houver uma alteração, sem precisar reiniciar o aplicativo.
      retry:
        initial-interval: 3000
        max-interval: 9000
        max-attempts: 1
    bus:
      refresh:
        enabled: true
      env:
        enabled: true
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de Kafka
  # --------------------------------------------------
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de actuator
  # --------------------------------------------------
management:
  endpoints:
    web:
      base-path: /actuator # Define o path base dos endpoints do actuator (padrão /actuator)
      exposure:
        include: refresh,health,info,metrics,configprops,busenv,busrefresh,busshutdown # Expõe endpoints para monitoramento
  endpoint:
    health:
      show-details: always # Mostra detalhes completos de saúde
    configprops:
      show-values: always # Mostra valores das propriedades de configuração
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de Eureka Server
  # --------------------------------------------------
eureka:
  client:
    register-with-eureka: false # False = Diz ao servidor: "Não tente se registrar em nenhum outro eureka, você é o próprio servidor". (true em prod)
    fetch-registry: false # False = Diz: "Não tente baixar a lista de serviços de outros servidores eureka". (true em prod)
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de logging
  # --------------------------------------------------
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  # --------------------------------------------------


