  # --------------------------------------------------
  # Config de Config Client
  # --------------------------------------------------
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      profile: ${SPRING_PROFILES_ACTIVE:prod}
      fail-fast: true
      refresh:
        enable: true
      retry:
        initial-interval: 3000
        max-interval: 9000
        max-attempts: 1
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de actuator
  # --------------------------------------------------
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: refresh,health,info,metrics,configprops
  endpoint:
    health:
      show-details: always
    configprops:
      show-values: always
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de Eureka Server
  # --------------------------------------------------
eureka:
  client:
    register-with-eureka: false # False = Diz ao servidor: "Não tente se registrar em nenhum outro eureka, você é o próprio servidor". (true em prod)
    fetch-registry: false # False = Diz: "Não tente baixar a lista de serviços de outros servidores eureka". (true em prod)
  # --------------------------------------------------


  # --------------------------------------------------
  # Config de logging
  # --------------------------------------------------
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  # --------------------------------------------------


